// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krhddximfgpnlciakfga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaGRkeGltZmdwbmxjaWFrZmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDUwMzMsImV4cCI6MjA2NjAyMTAzM30.HnvBXVIKCUbbc83CW75EVpToHbAGugACHVhH1ty0AGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);